name: Update
on:
  schedule:
    - cron: '13 */4 * * *'  # This line means the action will run every 12 hour
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Install Chrome WebDriver
        run: |
          LATEST_CHROMEDRIVER_VERSION=120.0.6099.109
          curl -sS -o chromedriver_linux64.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chrome-headless-shell-linux64.zip"
          sudo unzip chromedriver_linux64.zip -d /usr/local/bin
          rm chromedriver_linux64.zip
      - name: Set chromedriver path
        run: |
          sudo ln -sf /usr/local/bin/chrome-headless-shell-linux64/chrome-headless-shell /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run bjbj
        run: python ${{ github.workspace }}/bj_tes.py
      - name: 提交
        run: |
          git config --local user.email "pantong1995@126.com"
          git config --local user.name "xiaotong1995"
          git add .
          git commit *.txt -m "Add generated file"
          #git pull --rebase
          git push -f
  job2:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Update README
          run: |
            echo "SMS backup /r Last updated: $(date)" > README.md
        - name: Commit and push if changed
          run: |
            git config --global user.email "pantong1995@126.com"
            git config --global user.name "xiaotong1995"
            git commit -am "Update README" || exit 0
            git push origin main -f 
      needs: job1
